### PR TITLE
ci: Build with Eask 

### PR DESCRIPTION
**Pull request by jcs090218**
CI improvements! :)

### CODE REVIEW

**Review by zonuexe — APPROVED** [review]

**Comment by zonuexe** [comment]
@jcs090218 Thank you, I want to see Eask in action right away, so I merge this 😄

**Comment by zonuexe** [comment]
https://github.com/emacs-php/php-mode/actions/runs/6166874224

`windows-latest` tends to fail, so maybe we should tolerate failure.
Also, `macos-*` is also a little slow, so it might be a good idea to build only 28.2, 29.1, and snapshot.
I have older Emacs provided by my linux package manager so I'm testing them, but I believe macOS users are using newer Emacs.

**Comment by jcs090218** [comment]
> `windows-latest` tends to fail, so maybe we should tolerate failure.

Isn't the experimental flag  enough? 🤔 The mark will still be red ❌, but the badge will be green [CI](https://github.com/emacs-php/php-mode/actions/workflows/test.yml).

> Also, `macos-*` is also a little slow, so it might be a good idea to build only 28.2, 29.1, and snapshot.

I really like the way it acts now. It feels so consistent. 😁 

> I have older Emacs provided by my linux package manager so I'm testing them, but I believe macOS users are using newer Emacs.

Doesn't "manual testing" defeat the purpose of using CI/CD? 🤔  I mean I'll just let the machine run on its own! ;)

**Comment by zonuexe** [comment]
> Isn't the experimental flag enough? 🤔 The mark will still be red ❌, but the badge will be green CI.

👍

**Pull request merged**
