### PR TITLE
Fix #524: Change test for issue 443 to handle changed comment delimiter in emacs 27

### LINKED ISSUE #524: Failing test for issue 443 on emacs 27
The test for issue 443 fails on emacs 27 (an on emacs-git-snapshot-travis) because`*/` is considered separately as a comment delimiter. This is the difference in the output of the ert test:

afbeelding

@zonuexe Do you know an easy way to make this test pass on emacs 27? We could make a separate `issue-443-emacs-27.php` and `issue-443-emacs-27.php.faces` and then check the emacs version when running the tests, but I hope there is a more elegant solution. :)

Thanks!

### PR DESCRIPTION
**Pull request by mallt**
This PR fixes #524 by handling the changed comment delimiter in emacs 27.

### CODE REVIEW

**Comment by mallt** [comment]
@zonuexe Thanks for the change in the `with-php-mode-test` macro! It seems however if the `:faces` condition evaluates to `t` a `(wrong-type-argument sequencep t)` error is raised during test execution on older emacs versions.

Do you know how we can circumvent this error? Thanks!

**Comment by zonuexe** [comment]
@mallt I'm sorry, that was my mistake at #526, I just fixed in #528. Could you rebase this PR?

**Comment by mallt** [comment]
@zonuexe Thanks a lot for the fix! All checks are green now. :)

**Comment by zonuexe** [comment]
@mallt Thank you!

**Pull request merged**
